# Generated by Django 4.2.5 on 2023-10-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=40, null=True)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warden_name', models.CharField(max_length=50)),
                ('warden_address', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_type', models.CharField(max_length=50)),
                ('no_of_species', models.IntegerField()),
                ('game_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.game_park')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('wild_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.wild')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('received_by', models.CharField(blank=True, max_length=40, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.visitor')),
            ],
        ),
        migrations.AddField(
            model_name='game_park',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.warden'),
        ),
    ]
