# Generated by Django 4.2.5 on 2023-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='warden_photo',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
