# Generated by Django 4.2.5 on 2023-11-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_warden_warden_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warden',
            name='warden_photo',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
    ]
